#! /bin/sh

sxhkd &
compton &
feh --bg-fill ~/.wallpaper.jpg &
(cat ~/.cache/wal/sequences &) & 
setxkbmap -layout us -variant altgr-intl -option caps:escape &

if xrandr | grep -q 'DP-2 connected'; then
    bspc monitor DP-2 -d I II III IV V VI VII VIII IX
    bspc monitor eDP-1 -d X
    bspc wm -O DP-2 eDP-1
else
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi


bspc config border_width     4
bspc config window_gap		 12
#bspc config top_padding 	 5
bspc config bottom_padding 	 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config single_monocle	     true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
nm-applet &
blueman-tray &
